builders:
  xson_builder:
    import: "package:xson_builder/builder.dart"
    builder_factories:
    - xsonBuilder
    build_extensions: {".dart": [".xson.dart"]}
    auto_apply: root_package
    build_to: source
    runs_before: ["json_serializable"]