name: xson_builder
description: >-
  A library to help you easily generate dart json bean.
version: 1.0.3
homepage: https://github.com/Arxing/dart-xson_builder
author: Arxing <meiswind711108@gmail.com>
pubpage: https://pub.dev/packages/xson_builder

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  path: ^1.6.0
  xson: ^1.0.4
  named_mode: ^1.0.2+1
  dartpoet: ^1.0.5+4
  type_translator: ^1.0.1+1
  xson_annotation: ^1.0.2+1
  source_gen: ^0.9.4+5
  build: ^1.2.1
  xfile: ^1.1.0
  analyzer: '>=0.37.1 <0.39.0'

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0
  build_runner: ^1.6.7
  build_test: ^0.10.3
  json_serializable: ^3.2.2
  json_annotation: ^3.0.0

